language: android
jdk:
  - oraclejdk11
  
sudo: false

android:
  components:
    - build-tools-30.0.3
    - android-30
    - extra-android-m2repository
    
before_script:
  - chmod +x gradlew

script:
  - ./gradlew assembleRelease

